name: 01 Info Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4
      - name: Skripte ausführbar machen
        run: chmod +x scripts/*.sh
      - name: Info Skript starten
        run: bash scripts/01_show_info.sh